// mnfst-types: generate manifest.d.ts for a Manifest project.
//
// Reads ./manifest.json, samples each data source (CSV / JSON / YAML or
// Appwrite-table config), and writes a single manifest.d.ts that contains
// the static ambient declarations plus a project-specific augmentation of
// the ManifestSources interface.
//
// Re-running the CLI overwrites the augmentation block (between the
// AUGMENTATION:start / AUGMENTATION:end markers in the template).

import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { dirname, join, resolve, isAbsolute } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

const PACKAGE_ROOT = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_PATH = join(PACKAGE_ROOT, 'template', 'manifest.d.ts');

// ---------------------------------------------------------------------------
// CLI entry
// ---------------------------------------------------------------------------

export async function main(argv) {
    const opts = parseArgs(argv);

    if (opts.help) {
        printHelp();
        return;
    }

    const cwd = process.cwd();
    const manifestPath = resolve(cwd, opts.manifest);

    if (!existsSync(manifestPath)) {
        throw new Error(`manifest.json not found at ${manifestPath}`);
    }

    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    const projectRoot = dirname(manifestPath);

    const augmentation = await buildAugmentation(manifest, projectRoot);
    const template = readFileSync(TEMPLATE_PATH, 'utf8');
    const output = applyAugmentation(template, augmentation);

    const outPath = resolve(cwd, opts.out);
    writeFileSync(outPath, output);
    console.log(`mnfst-types: wrote ${outPath}`);

    if (opts.init) {
        const jsconfigPath = resolve(cwd, 'jsconfig.json');
        if (existsSync(jsconfigPath)) {
            console.log(`mnfst-types: jsconfig.json already exists, leaving it alone`);
        } else {
            writeFileSync(jsconfigPath, defaultJsconfig());
            console.log(`mnfst-types: wrote ${jsconfigPath}`);
        }
    }
}

function parseArgs(argv) {
    const opts = {
        manifest: 'manifest.json',
        out: 'manifest.d.ts',
        init: false,
        help: false
    };
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--help' || a === '-h') opts.help = true;
        else if (a === '--init') opts.init = true;
        else if (a === '--manifest') opts.manifest = argv[++i];
        else if (a === '--out') opts.out = argv[++i];
        else if (a.startsWith('--manifest=')) opts.manifest = a.slice('--manifest='.length);
        else if (a.startsWith('--out=')) opts.out = a.slice('--out='.length);
    }
    return opts;
}

function printHelp() {
    console.log(`mnfst-types — generate manifest.d.ts from a Manifest project

Usage:
  npx mnfst-types [options]

Options:
  --manifest <path>   Path to manifest.json (default: ./manifest.json)
  --out <path>        Output .d.ts path (default: ./manifest.d.ts)
  --init              Also write a baseline jsconfig.json (only if missing)
  -h, --help          Show this message
`);
}

function defaultJsconfig() {
    return JSON.stringify({
        compilerOptions: {
            target: 'es2022',
            module: 'es2022',
            moduleResolution: 'node',
            checkJs: true,
            allowJs: true,
            noEmit: true,
            strict: false,
            lib: ['es2022', 'dom']
        },
        include: ['**/*.js', 'manifest.d.ts'],
        exclude: ['node_modules', 'dist']
    }, null, 2) + '\n';
}

// ---------------------------------------------------------------------------
// Template augmentation
// ---------------------------------------------------------------------------

const START_MARKER = '// AUGMENTATION:start';
const END_MARKER = '// AUGMENTATION:end';

function applyAugmentation(template, body) {
    const startIdx = template.indexOf(START_MARKER);
    const endIdx = template.indexOf(END_MARKER);
    if (startIdx === -1 || endIdx === -1) {
        throw new Error('Template is missing AUGMENTATION:start / AUGMENTATION:end markers');
    }
    // Find the end of the start-marker line and the start of the end-marker line.
    const startLineEnd = template.indexOf('\n', startIdx) + 1;
    // Walk back from endIdx to the previous newline so we replace whole lines.
    let endLineStart = endIdx;
    while (endLineStart > 0 && template[endLineStart - 1] !== '\n') endLineStart--;

    const before = template.slice(0, startLineEnd);
    const after = template.slice(endLineStart);

    const generatedHeader = [
        '// Generated by `npx mnfst-types`. Do not edit by hand —',
        '// hand-edits between AUGMENTATION:start and AUGMENTATION:end are',
        '// overwritten on regeneration.',
        '// ---------------------------------------------------------------------------',
        ''
    ].join('\n');

    return before + generatedHeader + body + '\n' + after;
}

// ---------------------------------------------------------------------------
// Augmentation builder
// ---------------------------------------------------------------------------

async function buildAugmentation(manifest, projectRoot) {
    const data = manifest && typeof manifest === 'object' ? manifest.data : null;
    if (!data || typeof data !== 'object' || Object.keys(data).length === 0) {
        return [
            'declare global {',
            '    // No data sources declared in manifest.json.',
            '}',
            'export {};'
        ].join('\n');
    }

    const sourceTypes = [];
    const augmentations = [];

    for (const [name, config] of Object.entries(data)) {
        const inferred = await inferSourceType(name, config, projectRoot);
        if (!inferred) continue;
        sourceTypes.push(inferred.typeBlock);
        augmentations.push(`        ${jsonKey(name)}: ${inferred.augmentationType};`);
    }

    const lines = [];
    lines.push('// ---------------------------------------------------------------------------');
    lines.push('// Inferred row types for each data source.');
    lines.push('// ---------------------------------------------------------------------------');
    lines.push('');
    for (const block of sourceTypes) {
        lines.push(block);
        lines.push('');
    }
    lines.push('declare global {');
    lines.push('    interface ManifestSources {');
    lines.push.apply(lines, augmentations);
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('export {};');
    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Source-shape inference
// ---------------------------------------------------------------------------

async function inferSourceType(name, config, projectRoot) {
    const safeName = toTypeName(name);

    // Appwrite bucket (storage).
    if (config && typeof config === 'object' && config.appwriteBucketId) {
        return {
            typeBlock: `// ${name}: Appwrite storage bucket`,
            augmentationType: 'ManifestBucketSource'
        };
    }

    // Appwrite table.
    if (config && typeof config === 'object' && config.appwriteTableId) {
        const rowType = `Row_${safeName}`;
        const typeBlock = [
            `/** Row shape for $x.${name} (Appwrite table — extend as needed). */`,
            `export interface ${rowType} {`,
            `    $id: string;`,
            `    $createdAt?: string;`,
            `    $updatedAt?: string;`,
            `    [field: string]: unknown;`,
            `}`
        ].join('\n');
        return {
            typeBlock,
            augmentationType: `ManifestArraySource<${rowType}> & ManifestAppwriteTableOps<${rowType}>`
        };
    }

    // String — direct path/URL to a CSV/JSON/YAML file.
    if (typeof config === 'string') {
        const sample = sampleLocalFile(config, projectRoot);
        return formatLocalSource(name, safeName, sample);
    }

    // Object — could be a localized source (`locales:` or per-locale keys), an
    // HTTP endpoint with `url`, or an explicit defaultValue.
    if (config && typeof config === 'object') {
        if (typeof config.locales === 'string') {
            const sample = sampleLocalFile(config.locales, projectRoot);
            return formatLocalSource(name, safeName, sample);
        }

        // Per-locale keys — sample the first one we find.
        const localeKey = Object.keys(config).find((k) => /^[a-zA-Z]{2}(-[a-zA-Z]{2})?$/.test(k));
        if (localeKey && typeof config[localeKey] === 'string') {
            const sample = sampleLocalFile(config[localeKey], projectRoot);
            return formatLocalSource(name, safeName, sample);
        }

        if (typeof config.url === 'string') {
            return {
                typeBlock: `// ${name}: HTTP source — row type left generic.`,
                augmentationType: 'ManifestArraySource<any>'
            };
        }
    }

    return {
        typeBlock: `// ${name}: shape could not be inferred — leaving as ManifestArraySource<any>.`,
        augmentationType: 'ManifestArraySource<any>'
    };
}

function formatLocalSource(name, safeName, sample) {
    if (!sample) {
        return {
            typeBlock: `// ${name}: file not found at sample time.`,
            augmentationType: 'ManifestArraySource<any>'
        };
    }
    if (sample.kind === 'array') {
        const rowType = `Row_${safeName}`;
        const fields = formatFields(sample.fields, '    ');
        const typeBlock = [
            `/** Row shape for $x.${name} inferred from ${sample.path}. */`,
            `export interface ${rowType} {`,
            fields,
            `}`
        ].filter(Boolean).join('\n');
        return {
            typeBlock,
            augmentationType: `ManifestArraySource<${rowType}>`
        };
    }
    if (sample.kind === 'object') {
        const objType = `Obj_${safeName}`;
        const typeBlock = [
            `/** Object shape for $x.${name} inferred from ${sample.path}. */`,
            `export interface ${objType} ${formatObjectShape(sample.shape, '')}`
        ].join('\n');
        return {
            typeBlock,
            augmentationType: `ManifestObjectSource<${objType}>`
        };
    }
    return {
        typeBlock: `// ${name}: empty or unrecognized sample.`,
        augmentationType: 'ManifestArraySource<any>'
    };
}

// ---------------------------------------------------------------------------
// Local file sampling (CSV / JSON / YAML)
// ---------------------------------------------------------------------------

function sampleLocalFile(filePath, projectRoot) {
    if (typeof filePath !== 'string') return null;
    if (filePath.startsWith('http://') || filePath.startsWith('https://')) return null;
    const cleaned = filePath.replace(/^\/+/, '');
    const candidates = [
        isAbsolute(filePath) ? filePath : null,
        join(projectRoot, cleaned),
        join(projectRoot, filePath)
    ].filter(Boolean);

    let resolved = null;
    for (const c of candidates) {
        try {
            if (existsSync(c) && statSync(c).isFile()) {
                resolved = c;
                break;
            }
        } catch (_) { /* skip */ }
    }
    if (!resolved) return null;

    const lower = resolved.toLowerCase();
    try {
        if (lower.endsWith('.csv')) return { ...sampleCsv(resolved), path: filePath };
        if (lower.endsWith('.json')) return { ...sampleJson(resolved), path: filePath };
        if (lower.endsWith('.yaml') || lower.endsWith('.yml')) return { ...sampleYaml(resolved), path: filePath };
    } catch (e) {
        return null;
    }
    return null;
}

function sampleCsv(path) {
    const text = readFileSync(path, 'utf8');
    const rows = parseCsv(text);
    if (rows.length === 0) return { kind: 'array', fields: {} };
    const header = rows[0];
    const sampleRows = rows.slice(1, 51);
    const firstHeader = (header[0] || '').toLowerCase();

    // Key-value mode: first column is `key`, second is `value`.
    if (firstHeader === 'key' && (header[1] || '').toLowerCase() === 'value') {
        const shape = {};
        for (const row of sampleRows) {
            if (!row[0]) continue;
            assignDottedKey(shape, row[0], row[1]);
        }
        return { kind: 'object', shape };
    }

    // Tabular: array of rows with the header as field names.
    const fields = {};
    for (const col of header) {
        if (!col) continue;
        fields[col] = inferFieldType(sampleRows.map((r) => r[header.indexOf(col)]));
    }
    return { kind: 'array', fields };
}

function sampleJson(path) {
    const data = JSON.parse(readFileSync(path, 'utf8'));
    if (Array.isArray(data)) {
        const sample = data.slice(0, 50);
        const fields = {};
        for (const item of sample) {
            if (item && typeof item === 'object' && !Array.isArray(item)) {
                for (const [k, v] of Object.entries(item)) {
                    if (!fields[k]) fields[k] = [];
                    fields[k].push(v);
                }
            }
        }
        const out = {};
        for (const [k, vals] of Object.entries(fields)) {
            out[k] = inferFieldTypeFromValues(vals);
        }
        return { kind: 'array', fields: out };
    }
    if (data && typeof data === 'object') {
        return { kind: 'object', shape: shapeFromValue(data, 0) };
    }
    return { kind: 'object', shape: {} };
}

function sampleYaml(path) {
    let yaml;
    try { yaml = require('js-yaml'); } catch {
        return null;
    }
    const data = yaml.load(readFileSync(path, 'utf8'));
    if (Array.isArray(data)) {
        return sampleJsonFromObject(data);
    }
    if (data && typeof data === 'object') {
        return { kind: 'object', shape: shapeFromValue(data, 0) };
    }
    return { kind: 'object', shape: {} };
}

function sampleJsonFromObject(arr) {
    const sample = arr.slice(0, 50);
    const fields = {};
    for (const item of sample) {
        if (item && typeof item === 'object' && !Array.isArray(item)) {
            for (const [k, v] of Object.entries(item)) {
                if (!fields[k]) fields[k] = [];
                fields[k].push(v);
            }
        }
    }
    const out = {};
    for (const [k, vals] of Object.entries(fields)) {
        out[k] = inferFieldTypeFromValues(vals);
    }
    return { kind: 'array', fields: out };
}

// ---------------------------------------------------------------------------
// CSV parsing (header + rows, RFC-4180-ish: handles quotes and escapes)
// ---------------------------------------------------------------------------

function parseCsv(text) {
    const rows = [];
    let row = [];
    let field = '';
    let inQuotes = false;

    for (let i = 0; i < text.length; i++) {
        const ch = text[i];
        if (inQuotes) {
            if (ch === '"') {
                if (text[i + 1] === '"') { field += '"'; i++; }
                else { inQuotes = false; }
            } else {
                field += ch;
            }
            continue;
        }
        if (ch === '"') { inQuotes = true; continue; }
        if (ch === ',') { row.push(field); field = ''; continue; }
        if (ch === '\r') continue;
        if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; continue; }
        field += ch;
    }
    if (field.length > 0 || row.length > 0) {
        row.push(field);
        rows.push(row);
    }
    return rows.filter((r) => r.length > 1 || (r.length === 1 && r[0] !== ''));
}

function assignDottedKey(target, dottedKey, value) {
    const parts = dottedKey.split('.');
    let cur = target;
    for (let i = 0; i < parts.length - 1; i++) {
        const part = parts[i];
        const isIndex = /^\d+$/.test(part);
        if (isIndex) {
            // Numeric segment indicates an array element; we still model as object for typing.
            if (!cur._array) cur._array = true;
        }
        if (!cur[part] || typeof cur[part] !== 'object') cur[part] = {};
        cur = cur[part];
    }
    const leaf = parts[parts.length - 1];
    cur[leaf] = inferLiteralType(value);
}

// ---------------------------------------------------------------------------
// Type inference helpers
// ---------------------------------------------------------------------------

function inferFieldType(values) {
    return inferFieldTypeFromValues(values);
}

function inferFieldTypeFromValues(values) {
    let sawNumber = false, sawBool = false, sawString = false, sawNull = false, sawObject = false, sawArray = false;
    for (const v of values) {
        if (v === undefined || v === null || v === '') { sawNull = true; continue; }
        if (typeof v === 'number') { sawNumber = true; continue; }
        if (typeof v === 'boolean') { sawBool = true; continue; }
        if (Array.isArray(v)) { sawArray = true; continue; }
        if (typeof v === 'object') { sawObject = true; continue; }
        if (typeof v === 'string') {
            const t = v.trim();
            if (t === 'true' || t === 'false') { sawBool = true; continue; }
            if (t !== '' && !isNaN(Number(t))) { sawNumber = true; continue; }
            sawString = true;
        }
    }
    const parts = [];
    if (sawString) parts.push('string');
    if (sawNumber) parts.push('number');
    if (sawBool) parts.push('boolean');
    if (sawArray) parts.push('unknown[]');
    if (sawObject) parts.push('Record<string, unknown>');
    if (sawNull) parts.push('null');
    if (parts.length === 0) return 'string';
    return parts.join(' | ');
}

function inferLiteralType(value) {
    if (value === undefined || value === null || value === '') return 'string';
    const s = String(value).trim();
    if (s === 'true' || s === 'false') return 'boolean';
    if (!isNaN(Number(s))) return 'number';
    return 'string';
}

function shapeFromValue(value, depth) {
    if (depth > 5 || value === null || value === undefined) return 'unknown';
    if (Array.isArray(value)) {
        if (value.length === 0) return 'unknown[]';
        const inner = shapeFromValue(value[0], depth + 1);
        if (typeof inner === 'object' && inner !== null) {
            return inlineShape(inner) + '[]';
        }
        return inner + '[]';
    }
    if (typeof value === 'object') {
        const out = {};
        for (const [k, v] of Object.entries(value)) {
            out[k] = shapeFromValue(v, depth + 1);
        }
        return out;
    }
    return typeof value;
}

function inlineShape(tree) {
    if (typeof tree === 'string') return tree;
    if (typeof tree !== 'object' || tree === null) return 'unknown';
    const parts = [];
    for (const [k, v] of Object.entries(tree)) {
        if (k === '_array') continue;
        parts.push(`${jsonKey(k)}: ${inlineShape(v)}`);
    }
    return parts.length === 0 ? 'Record<string, unknown>' : `{ ${parts.join('; ')} }`;
}

// ---------------------------------------------------------------------------
// Type rendering
// ---------------------------------------------------------------------------

function formatFields(fields, indent) {
    return Object.entries(fields)
        .map(([k, t]) => `${indent}${jsonKey(k)}: ${t};`)
        .join('\n');
}

function formatObjectShape(shape, indent) {
    if (typeof shape === 'string') return shape;
    if (typeof shape !== 'object' || shape === null) return 'unknown';
    const inner = indent + '    ';
    const lines = [];
    for (const [k, v] of Object.entries(shape)) {
        if (k === '_array') continue;
        const formatted = typeof v === 'object' && v !== null && !Array.isArray(v)
            ? formatObjectShape(v, inner)
            : v;
        lines.push(`${inner}${jsonKey(k)}: ${formatted};`);
    }
    return `{\n${lines.join('\n')}\n${indent}}`;
}

function jsonKey(name) {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function toTypeName(name) {
    return name.replace(/[^A-Za-z0-9_$]/g, '_');
}
