/**
 * Real-Chrome proof for the publish-time utility CSS work (PERF-PRIMITIVES-DESIGN.md §15).
 *
 * Boots the src/ dev server, loads the real docs homepage in puppeteer, and
 * counts how many times #manifest-styles' content changes in the first 5s —
 * once cold (today's behavior) and once with a static utilities sheet
 * (`<style data-mnfst-utilities>`, generated by scripts/utilities-static.mjs)
 * present from the start. Prints both counts; the static-sheet run should be
 * far lower since compile() skips every class the sheet already covers.
 *
 * Run: node tests/e2e/utilities-static.e2e.mjs
 */
import { spawn } from 'child_process'
import http from 'http'
import path from 'path'
import { fileURLToPath } from 'url'
import { execFileSync } from 'child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import puppeteer from 'puppeteer'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..', '..')
const PORT = process.env.UTIL_E2E_PORT || 5098

const wait = (ms) => new Promise((r) => setTimeout(r, ms))

function startServer(onAlreadyRunning) {
    const proc = spawn('node', ['packages/run/serve.mjs', 'src', '--port', String(PORT)],
        { cwd: ROOT, stdio: ['ignore', 'pipe', 'pipe'] })
    let out = ''
    const sniff = (chunk) => {
        out += String(chunk)
        const m = out.match(/already running at (http:\/\/localhost:\d+)/)
        if (m) onAlreadyRunning(m[1])
    }
    proc.stdout.on('data', sniff)
    proc.stderr.on('data', sniff)
    return proc
}

function ping(url) {
    return new Promise((resolve) => {
        const req = http.get(url, (res) => { res.resume(); resolve(res.statusCode === 200) })
        req.on('error', () => resolve(false))
        req.setTimeout(1000, () => { req.destroy(); resolve(false) })
    })
}

// Counts #manifest-styles content changes over the observation window. Set up
// via evaluateOnNewDocument so it's armed before the plugin's own script runs.
const COUNTER_SCRIPT = `
(function () {
  window.__styleWriteCount = 0;
  let attached = false;
  const attach = (el) => {
    if (attached) return;
    attached = true;
    new MutationObserver(() => { window.__styleWriteCount++; })
      .observe(el, { childList: true, characterData: true, subtree: true });
  };
  const existing = document.getElementById('manifest-styles');
  if (existing) attach(existing);
  // Observe \`document\` itself (not documentElement, which may not exist yet
  // this early in a fresh document) so this is armed no matter how soon
  // evaluateOnNewDocument runs relative to HTML parsing.
  new MutationObserver((mutations) => {
    for (const m of mutations) {
      for (const node of m.addedNodes) {
        if (node.id === 'manifest-styles') attach(node);
      }
    }
  }).observe(document, { childList: true, subtree: true });
})();
`

async function measure(browser, { withStaticSheet, staticCss }) {
    const page = await browser.newPage()
    // Isolate each run to the live JIT pipeline — without this, the 2nd run
    // would replay the 1st run's localStorage cache (a real, separate code
    // path — manifest.utilities.cache.js — exercised by the happy-dom test
    // instead) and conflate "cache replay" with "live compile()" in the count.
    await page.evaluateOnNewDocument("try { localStorage.clear(); } catch (e) {}")
    await page.evaluateOnNewDocument(COUNTER_SCRIPT)
    if (withStaticSheet) {
        const escaped = staticCss.replace(/<\/style>/g, '<\\/style>')
        await page.evaluateOnNewDocument(`
          (function () {
            const inject = () => {
              const style = document.createElement('style');
              style.setAttribute('data-mnfst-utilities', '');
              style.textContent = ${JSON.stringify(escaped)};
              document.head.insertBefore(style, document.head.firstChild);
            };
            // document.head doesn't exist yet this early in a fresh document —
            // wait for it (mirrors what the real hosting-injected <link> would
            // just have from being written into the HTML before any script runs).
            if (document.head) {
              inject();
            } else {
              new MutationObserver((_, obs) => {
                if (document.head) { obs.disconnect(); inject(); }
              }).observe(document.documentElement || document, { childList: true, subtree: true });
            }
          })();
        `)
    }
    await page.goto(`http://localhost:${PORT}/`, { waitUntil: 'domcontentloaded' })
    await wait(5000)
    const result = await page.evaluate(() => {
        const el = document.getElementById('manifest-styles')
        const compiler = window.ManifestUtilities
        return {
            writes: window.__styleWriteCount,
            finalCssLength: el ? el.textContent.length : 0,
            coveredCount: compiler && compiler.staticUtilitiesCoveredClasses ? compiler.staticUtilitiesCoveredClasses.size : 0,
        }
    })
    await page.close()
    return result
}

async function main() {
    let baseUrl = `http://localhost:${PORT}`
    let ownsServer = true
    const proc = startServer((existingUrl) => { baseUrl = existingUrl; ownsServer = false })

    try {
        let up = false
        for (let i = 0; i < 40 && !up; i++) {
            up = await ping(`${baseUrl}/`)
            if (!up) await wait(250)
        }
        if (!up) throw new Error(`dev server never came up at ${baseUrl}`)

        // Generate the static sheet the same way hosting/publish would.
        const tmp = mkdtempSync(path.join(tmpdir(), 'mnfst-utilities-e2e-'))
        const themePath = path.join(tmp, 'theme.css')
        const themeCss = [
            readFileSync(path.join(ROOT, 'src/styles/core/manifest.theme.css'), 'utf8'),
            readFileSync(path.join(ROOT, 'src/styles/utilities/manifest.utilities.css'), 'utf8'),
        ].join('\n')
        writeFileSync(themePath, themeCss)
        const outPath = path.join(tmp, 'out.css')
        execFileSync(process.execPath, [path.join(ROOT, 'scripts/utilities-static.mjs'), path.join(ROOT, 'src'), '--theme', themePath, '--out', outPath])
        const staticCss = readFileSync(outPath, 'utf8')
        console.log(`generated static sheet: ${staticCss.length} bytes`)

        const browser = await puppeteer.launch({ headless: 'new' })
        try {
            const cold = await measure(browser, { withStaticSheet: false })
            const withSheet = await measure(browser, { withStaticSheet: true, staticCss })
            console.log(`#manifest-styles content changes in first 5s — cold: ${cold.writes}, with static sheet: ${withSheet.writes}`)
            console.log(`final #manifest-styles CSS length — cold: ${cold.finalCssLength} chars, with static sheet: ${withSheet.finalCssLength} chars (${withSheet.coveredCount} classes recognized as covered)`)
        } finally {
            await browser.close()
            rmSync(tmp, { recursive: true, force: true })
        }
    } finally {
        if (ownsServer) proc.kill()
    }
}

main().catch((err) => {
    console.error(err)
    process.exit(1)
})
