/**
 * Manifest ambient type declarations.
 * https://manifestx.dev
 *
 * This file gives editors (VS Code, Cursor, JetBrains) and AI coding assistants
 * type information for Manifest's magic globals and data-source state. It is
 * intended to live in the project root and is regenerated by `npx mnfst-types`
 * to add project-specific augmentations to ManifestSources from manifest.json.
 *
 * Hand-edits below the AUGMENTATION marker will be overwritten on regeneration.
 */

// ---------------------------------------------------------------------------
// Data-source state and operators (attached to every $x.<source>)
// ---------------------------------------------------------------------------

/** Appwrite-style query expression returned by helper builders. */
export type ManifestQueryExpr = string;

/** Appwrite-style query helpers used with `$query([...])`. */
export interface ManifestQuery {
    equal(field: string, value: unknown): ManifestQueryExpr;
    notEqual(field: string, value: unknown): ManifestQueryExpr;
    lessThan(field: string, value: number | string): ManifestQueryExpr;
    lessThanEqual(field: string, value: number | string): ManifestQueryExpr;
    greaterThan(field: string, value: number | string): ManifestQueryExpr;
    greaterThanEqual(field: string, value: number | string): ManifestQueryExpr;
    between(field: string, start: number | string, end: number | string): ManifestQueryExpr;
    contains(field: string, value: string | string[]): ManifestQueryExpr;
    startsWith(field: string, value: string): ManifestQueryExpr;
    endsWith(field: string, value: string): ManifestQueryExpr;
    search(field: string, value: string): ManifestQueryExpr;
    isNull(field: string): ManifestQueryExpr;
    isNotNull(field: string): ManifestQueryExpr;
    select(fields: string[]): ManifestQueryExpr;
    orderAsc(field: string): ManifestQueryExpr;
    orderDesc(field: string): ManifestQueryExpr;
    limit(value: number): ManifestQueryExpr;
    offset(value: number): ManifestQueryExpr;
    cursorAfter(id: string): ManifestQueryExpr;
    cursorBefore(id: string): ManifestQueryExpr;
}

/** State flags exposed on every data source (array or object). */
export interface ManifestSourceState {
    /** True while the source is fetching for the first time or after a mutation. */
    readonly $loading: boolean;
    /** Last error from a load or mutation, or null. */
    readonly $error: Error | string | null;
    /** True once initial load has completed (success or failure). */
    readonly $ready: boolean;
}

/** Operators available on array-shaped sources (CSV tabular, JSON arrays, Appwrite tables). */
export interface ManifestArrayOps<T> {
    /** Substring match across the given fields. Returns matching items. */
    $search(term: string, ...fields: (keyof T & string)[]): T[];
    /**
     * Local sources: filter by an array of `Manifest.query.*` expressions and array methods.
     * Appwrite sources: server-side query, returns a Promise.
     */
    $query(expressions: ManifestQueryExpr[]): T[] | Promise<T[]>;
    /** Look up a single row whose `id` matches the current route param, if any. */
    $route(path?: string): T | undefined;
}

/** Mutations available on Appwrite-table sources. */
export interface ManifestAppwriteTableOps<T> {
    $create(values: Partial<T>): Promise<T>;
    $update(id: string, values: Partial<T>): Promise<T>;
    $delete(id: string): Promise<void>;
    $duplicate(id: string, overrides?: Partial<T>): Promise<T>;
}

/** Operations available on Appwrite-bucket (storage) sources. */
export interface ManifestAppwriteBucketOps {
    $url(fileId: string): string;
    $preview(fileId: string, opts?: Record<string, unknown>): string;
    $download(fileId: string): string;
    $openUrl(fileId: string): void;
    $openPreview(fileId: string): void;
    $openDownload(fileId: string): void;
    $upload(file: File | Blob, opts?: Record<string, unknown>): Promise<{ $id: string }>;
    $remove(fileId: string): Promise<void>;
    $filesFor(parentId: string, fieldName?: string): unknown[];
    $unlinkFrom(parentId: string, fileId: string): Promise<void>;
    $removeFrom(parentId: string, fileId: string): Promise<void>;
}

/**
 * The shape returned by `$x.<source>` for an array-of-rows source.
 * Behaves as a regular `T[]` (supports `map`, `filter`, `find`, etc.) plus
 * Manifest operators and state flags.
 */
export type ManifestArraySource<T> =
    & ReadonlyArray<T>
    & ManifestSourceState
    & ManifestArrayOps<T>
    & Partial<ManifestAppwriteTableOps<T>>;

/** The shape returned by `$x.<source>` for an object-shaped source (CSV key-value, JSON object, YAML map). */
export type ManifestObjectSource<T> = T & ManifestSourceState;

/** The shape returned by `$x.<source>` for an Appwrite storage bucket. */
export type ManifestBucketSource = ManifestSourceState & ManifestAppwriteBucketOps;

// ---------------------------------------------------------------------------
// Magic globals registered by Manifest plugins
// ---------------------------------------------------------------------------

/**
 * Project-specific data sources, keyed by the names declared in `manifest.json`'s
 * `data` property. Augmented by `npx mnfst-types` from manifest.json + sample
 * data (declarations appended below the AUGMENTATION marker).
 */
export interface ManifestSources {
    [sourceName: string]: ManifestArraySource<any> | ManifestObjectSource<any> | ManifestBucketSource;
}

/** `$auth` from the Appwrite auth plugin. Loose by design — auth API is broad. */
export interface ManifestAuth {
    readonly current: { $id: string; email?: string; name?: string;[k: string]: unknown } | null;
    readonly isAuthenticated: boolean;
    readonly isLoading: boolean;
    readonly currentTeam: { $id: string; name: string;[k: string]: unknown } | null;
    readonly teams: Array<{ $id: string; name: string;[k: string]: unknown }>;
    login(email: string, password?: string): Promise<unknown>;
    loginWithMagic(email: string): Promise<unknown>;
    loginWithOAuth(provider: string, opts?: Record<string, unknown>): Promise<unknown>;
    loginAsGuest(): Promise<unknown>;
    logout(): Promise<unknown>;
    [extra: string]: unknown;
}

/** `$locale` from the localization plugin. */
export interface ManifestLocale {
    readonly current: string;
    readonly available: string[];
    set(locale: string): void;
}

/** `$toast` from the toasts plugin. */
export interface ManifestToast {
    (message: string, opts?: { type?: 'info' | 'success' | 'warning' | 'error'; duration?: number }): void;
    info(message: string, opts?: Record<string, unknown>): void;
    success(message: string, opts?: Record<string, unknown>): void;
    warning(message: string, opts?: Record<string, unknown>): void;
    error(message: string, opts?: Record<string, unknown>): void;
    dismiss(id?: string): void;
}

/** `$colors` from the themes plugin. */
export interface ManifestTheme {
    readonly current: 'light' | 'dark' | 'system';
    set(theme: 'light' | 'dark' | 'system'): void;
    toggle(): void;
}

/** `$colors` from the colors plugin. */
export interface ManifestColors {
    [name: string]: string | ManifestColors;
}

/** `$colorpicker` from the colorpicker plugin. */
export interface ManifestColorpicker {
    open(opts?: Record<string, unknown>): void;
    close(): void;
    [extra: string]: unknown;
}

/** `$url` from the url-parameters plugin: read/write URL query params reactively. */
export interface ManifestUrl {
    get(name: string): string | null;
    set(name: string, value: string | null): void;
    has(name: string): boolean;
    [name: string]: unknown;
}

/** `$route` magic — true if the current route matches the given pattern. */
export type ManifestRoute = (pattern: string) => boolean;

/**
 * `$modify('attr')` — exposed in component HTML. Returns the value of an
 * attribute set on the parent component instance (Manifest's prop mechanism).
 */
export type ManifestModify = (attr: string) => string | undefined;

/** `$try(fn)` — run a callback and swallow any thrown error, returning undefined on failure. */
export type ManifestTry = <T>(fn: () => T) => T | undefined;

// ---------------------------------------------------------------------------
// Global declarations (what Alpine exposes inside `x-data`, `x-show`, etc.)
// ---------------------------------------------------------------------------

declare global {
    /** Project data sources registered in manifest.json. */
    const $x: ManifestSources;
    /** Match the current route against a pattern (e.g. `$route('/about')`). */
    const $route: ManifestRoute;
    /** Read a parent component attribute (Manifest's prop mechanism). */
    const $modify: ManifestModify;
    /** Run a callback safely, returning undefined on error. */
    const $try: ManifestTry;
    /** Appwrite auth plugin (only present when the plugin is loaded). */
    const $auth: ManifestAuth;
    /** Localization plugin. */
    const $locale: ManifestLocale;
    /** Toasts plugin. */
    const $toast: ManifestToast;
    /** Themes plugin. */
    const $colors: ManifestTheme;
    /** Colors plugin. */
    const $colors: ManifestColors;
    /** Colorpicker plugin. */
    const $colorpicker: ManifestColorpicker;
    /** URL parameters plugin. */
    const $url: ManifestUrl;

    /** Window-level Manifest namespace exposed by the loader. */
    interface Window {
        Manifest?: {
            loadPlugin(name: string, version?: string): Promise<unknown>;
            loadTailwind(version?: string): Promise<unknown>;
            getPluginUrl(name: string, version?: string): string;
        };
        Alpine?: unknown;
        __manifestLoaded?: unknown;
    }
}

// ---------------------------------------------------------------------------
// AUGMENTATION:start
// Project-specific declarations are appended below by `npx mnfst-types`.
// Do not hand-edit between the start/end markers — re-running the CLI
// regenerates this section from manifest.json + sample data.
// ---------------------------------------------------------------------------

// (No project augmentations yet — run `npx mnfst-types` to generate.)

// ---------------------------------------------------------------------------
// AUGMENTATION:end
// ---------------------------------------------------------------------------

export { };
